channels:
  - conda-forge
dependencies:
  - numpy
  - jupyter-server-proxy
  - code-server
  - bokeh
  - python
  - pandas
  - scipy
  - numpy
  - matplotlib
  - pip
  - pip:
    - jupyter-server-proxy
    - nbserverproxy
